
---
- name: Configure Frontend Server
  hosts: 172.31.85.99
  become: true

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and Enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true

    - name: Remove default Nginx content
      file:
        path: /usr/share/nginx/html/
        state: absent
        recurse: true

    - name: Download frontend content
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /tmp/frontend.zip

    - name: Extract frontend content
      unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html/

    - name: Create Nginx Reverse Proxy Configuration
      blockinfile:
        path: /etc/nginx/default.d/roboshop.conf
        block: |
          proxy_http_version 1.1;
          location /images/ {
            expires 5s;
            root   /usr/share/nginx/html;
            try_files $uri /images/placeholder.jpg;
          }
          location /api/catalogue/ { proxy_pass http://localhost:8080/; }
          location /api/user/ { proxy_pass http://localhost:8080/; }
          location /api/cart/ { proxy_pass http://localhost:8080/; }
          location /api/shipping/ { proxy_pass http://localhost:8080/; }
          location /api/payment/ { proxy_pass http://localhost:8080/; }
          location /health {
            stub_status on;
            access_log off;
          }

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
















